package core;

import utils.Join;
import utils.Pos;

import static fearlessParser.TokenKind.*;
import static offensiveUtils.Require.*;

import java.util.*;

import offensiveUtils.EqTransparent;

public sealed interface E{
  default Pos pos(){ return src().inner.pos(); }
  default TSpan span(){ return src().inner.span(); }
  Src src();
  record X(String name, Src src) implements E{
    public X{ assert name.equals("-") || validate(name, "parameter name",LowercaseId); }
    public String toString(){ return name;}}
  record Type(T.RCC type, Src src) implements E{
    public Type{ assert nonNull(type,src); }
    public String toString(){ return type.toString();}
  }
  //infName is intentionally lost when a package's public API is cached to disk and reloaded: a package's user must not know whether a name was autogenerated.
  record Literal(RC rc, TName name, List<B> bs, List<T.C> cs, String thisName, List<M> ms, Src src, boolean infName, EqTransparent<Boolean> onlyImmCapture) implements E{
    public Literal(RC rc, TName name, List<B> bs, List<T.C> cs, String thisName, List<M> ms, Src src, boolean infName){ this(rc,name,bs,cs,thisName,ms,src,infName,new EqTransparent<>(false)); }
    public Literal{
      assert unmodifiableDistinct(bs,"L.bs");
      assert unmodifiableDistinct(cs,"L.cs");
      assert unmodifiableDistinct(ms, "L.ms");
      assert nonNull(rc,name,thisName,src,onlyImmCapture);
      assert eq(bs.size(), name.arity(),"Type arity");
    }
    public Literal withMs(List<M> ms){ return new Literal(rc,name,bs,cs,thisName,ms,src,infName,onlyImmCapture); }
    public Literal withRC(RC rc){ return new Literal(rc,name,bs,cs,thisName,ms,src,infName,onlyImmCapture); }
    public String toString(){
      return rc+" "+name.s()+Join.of(bs,"[",",","]","")+":"+Join.of(cs,"",", ","","")+"{'"+thisName+" "+Join.of(ms,"","; ","","")+"}";
    }
  }
  record Call(E e, MName name, RC rc, List<T> targs, List<E> es, EqTransparent<T> expectedRes, Src src) implements E{
    public Call{
      assert nonNull(e,name,rc,targs,expectedRes,src);
      assert unmodifiable(es, "E.Call.es");
      assert unmodifiable(targs, "E.Call.targs");
    }
    public String toString(){
      String _targs= Join.of(targs,"["+rc+",",",","","["+rc);
      String _es= Join.of(es,"(",", ",")","");
      return ""+e+name+_targs+"]"+_es;
    }
  }
}